version: '3'

networks:
  nginx-php81-mysql8:

services:
  #nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/symfony-DDD
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81-service
      - mysql8-service
    networks:
      - nginx-php81-mysql8

  #php
  php81-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php81-container
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/symfony-DDD
    networks:
      - nginx-php81-mysql8


  #mysql
  mysql8-service:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "4306:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: DDD
      MYSQL_ROOT_PASSWORD: 101910
      MYSQL_PASSWORD: 101910
    networks:
      - nginx-php81-mysql8


volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###